---
title: "Experiment on soft labels"
format: html
---


## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}

N <- 50
eval_soft <- function(r) {
  x1 <- rnorm(N, mean = -0.5)
  x2 <- rnorm(N, mean = 0.5)
  y <- c(rep(1-r, N), rep( r, N))
  X <- matrix(c(x1, x2), ncol = 1)
  df <- data.frame(x = c(x1, x2), y = y)
  mod <- suppressWarnings( glm(y ~ x, data = df, family = binomial()))
  w <- coef(mod)
  a <- w[1]
  b <- w[2]
  #print(sprintf("b = %f", b))
  
  f <- function(x) {
    t <- b* x + a
    l1 <- -log1p( exp(t))
    l2 <- -log1p( exp(-t))
    d1 <- dnorm(x, -0.5)
    d2 <- dnorm(x, 0.5)
    ld1 <- -log1p(exp(-x))
    ld2 <- -log1p(exp(x))
    #print(c(d2, l1, ld2))
    return(d2 *  ( l1 - ld2)^2)
  }
  f1 <- function(x) {
    t <- b* x + a
    k1 <- 1 / (1 + exp(-t))
    k2 <- 1 / (1 + exp(t))
    l1 <- -log1p( exp(-t))
    l2 <- -log1p( exp(t))
   
    d1 <- dnorm(x, -0.5)
    d2 <- dnorm(x, 0.5)
    lp1 <- -log1p(exp(-x))
    lp2 <- -log1p(exp(x))
    p1 <- 1 / (1 + exp(-x))
    p2 <- 1 / (1 + exp(x))
    #print(c(d2, l1, ld2))
    return(d2 * (p1 *  ( lp1 - l1) + p2 * (lp2 - l2)))
  }
  
  integrate(f1, -5, 5)$value
}
```

```{r eval1}
M <- 10000
s <- seq(0.9, 1, length.out = M)
sv <- lapply(s, eval_soft)
#print(sv)
#plot(1:200, as.numeric(sv))
df <- data.frame(x = s, y = as.numeric(sv))
library(ggplot2)

ggplot(df, aes(x =x , y =y )) + 
 # geom_point() +
  geom_smooth()
```

