---
title: "Dataset properties"
author: "Ondrej Such"
date: "2025-03-01"
format: pdf
---

## Number of classes


First, let us retrieve the number of classes for each dataset 
```{r number of classes}
source("glm1.R")
library(purrr)
library(knitr)

# df <- map(files[1], function(f) {
df <- map("dna", function(f) {
    dfs <- read_wlws(800, f, 0)  
    data.frame(dataset = f, K = max(dfs$train$class_id))
}) |> list_rbind()

e = new.env(parent= emptyenv())
for (i in 1:nrow(df)) {
    e[[df$dataset[i] ]] = df$K[i]
}

kable(df)
```

Now we check for linear separation of classes

```{r separation}
library(CVXR)

df_sep <- map(1:nrow(df), function(r) {
# df_sep <- map(1:1, function(r) {
    map(0:19, function(run) {
        print(sprintf("%s %d", df$dataset[r], run))
        dfs <- read_wlws(800, df$dataset[r], run)
        dft <- dfs$train
        X <- as.matrix(dplyr::select(dft, -class_id))
        K <- df$K[r]

        w <- Variable(ncol(dft) - 1, cols = 1)
        b <- Variable(1)

        tot <- 0 
        for (i in 1:(K-1)) {
            for (j in (i+1):K) {
                X1 <- X[dft$class_id == i,]
                X2 <- X[dft$class_id == j,]
                objective <- Minimize(sum_squares(w))
                constraints <- list (X1 %*% w + b <= -1,
                                     X2 %*% w + b >= 1)
                problem  <- Problem(objective, 
                        constraints = constraints)
                result <- solve(problem, "ECOS")
                if(result$status == "optimal") {
                    tot <- tot + 1
                } else {
                    if(result$status != "infeasible") {
                        print(result$status)
                    }
 #                 stopifnot(result$status == "infeasible")

                }
            }
        }
#        stopifnot(F)
        data.frame(dataset = df$dataset[r], K = K, tot = tot)
    }) |> list_rbind()
}) |> list_rbind()
```

Now we output the summary statistics to a table

```{r output}
library(xtable)
library(knitr)

df_sep_sum <- df_sep |> group_by(dataset, K ) |> summarize(mean(tot * 2 / (K * (K-1))))

#sink("data-tbl.tex")
(kable(df_sep_sum, label = "tab:sep-sum", digits = 2,
    caption = "Average number of binary subproblems that are separable for a given dataset"))
#sink()
```

